version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mypharmacy-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PW}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PW}
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  app:
    build: .
    container_name: mypharmacy-app
    ports:
      - "8080:8081"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      KAKAO_REST_API_KEY: "${KAKAO_REST_API_KEY}"

volumes:
  dbdata:
