name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때만 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 설정 (Spring Boot 17 기준)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3. gradlew 실행 권한 부여
      - name: Set execute permission for gradlew
        run: chmod +x ./gradlew

      # 4. Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build

      # 5. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6. Docker 이미지 빌드
      - name: Build Docker image
        run: docker build -t mayjoonll/pharmacy-app:latest .

      # 7. Docker 이미지 푸시
      - name: Push Docker image
        run: docker push mayjoonll/pharmacy-app:latest

      # 8. EC2 서버에 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull mayjoonll/pharmacy-app:latest
            docker stop pharmacy-app || true
            docker rm pharmacy-app || true
            docker run -d --name pharmacy-app -p 8080:8080 mayjoonll/pharmacy-app:latest
