name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때만 실행

env:
  KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 설정 (Spring Boot 17 기준)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3. gradlew 실행 권한 부여
      - name: Set execute permission for gradlew
        run: chmod +x ./gradlew

      # 4. Gradle 빌드 (테스트 제외)
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 5. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6. Docker 이미지 빌드
      - name: Build Docker image
        run: docker build -t mayjoonll/pharmacy-app:latest .

      # 7. Docker 이미지 푸시
      - name: Push Docker image
        run: docker push mayjoonll/pharmacy-app:latest

      # 8. SSH 키 생성 (수동 파일 생성 단계 제거됨)
      # 키 파일 생성 대신, appleboy/ssh-action의 'key' 파라미터로 직접 전달합니다.

      # 9. EC2 서버에 배포 (SSH 인증 개선 및 환경변수 전달)
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          # key_path 대신 'key' 파라미터로 GitHub Secret 값을 직접 전달
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 최신 이미지 풀
            docker pull mayjoonll/pharmacy-app:latest

            # 기존 컨테이너 중지 (실행 중이 아니어도 오류를 무시)
            docker stop pharmacy-app || true

            # 기존 컨테이너 삭제 (존재하지 않아도 오류를 무시)
            docker rm pharmacy-app || true

            # 새 컨테이너 실행 및 환경 변수 전달
            # -e 옵션을 사용하여 KAKAO_REST_API_KEY를 컨테이너 내부로 전달
            docker run -d \
              --name pharmacy-app \
              -p 8080:8080 \
              -e KAKAO_REST_API_KEY='${{ secrets.KAKAO_REST_API_KEY }}' \
              mayjoonll/pharmacy-app:latest